
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "./(context)/query-client";
import { ContextProvider } from "./(context)/context";

import { SessionProvider } from "next-auth/react";
import ProtectedRoute from "@/protected-route";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
       <QueryProvider>
        <ContextProvider>
          <SessionProvider>
          <ProtectedRoute>
            {children}
          </ProtectedRoute>
     
          </SessionProvider>
         
        </ContextProvider>
          
       </QueryProvider>
      
     
  
        
      </body>
    </html>
  );
}
